import { USER_ROLES } from "./constants";

export const PERMISSIONS = {
  CAN_POST_JOB: "CAN_POST_JOB",
  CAN_EDIT_JOB: "CAN_EDIT_JOB",
  CAN_DELETE_JOB: "CAN_DELETE_JOB",
  CAN_VIEW_APPLICANTS: "CAN_VIEW_APPLICANTS",
  CAN_UPDATE_APPLICATION_STATUS: "CAN_UPDATE_APPLICATION_STATUS",
  CAN_APPLY_TO_JOB: "CAN_APPLY_TO_JOB",
  CAN_SAVE_JOB: "CAN_SAVE_JOB",
  CAN_UPLOAD_RESUME: "CAN_UPLOAD_RESUME",
  CAN_MESSAGE_EMPLOYER: "CAN_MESSAGE_EMPLOYER",
  CAN_APPROVE_COMPANY: "CAN_APPROVE_COMPANY",
  CAN_MANAGE_USERS: "CAN_MANAGE_USERS",
  CAN_VIEW_AUDIT_LOGS: "CAN_VIEW_AUDIT_LOGS",
  CAN_BAN_USER: "CAN_BAN_USER",
  CAN_SEE_ANALYTICS: "CAN_SEE_ANALYTICS",
};

export const ROLE_PERMISSIONS = {
  [USER_ROLES.APPLICANT]: [
    PERMISSIONS.CAN_APPLY_TO_JOB,
    PERMISSIONS.CAN_SAVE_JOB,
    PERMISSIONS.CAN_UPLOAD_RESUME,
    PERMISSIONS.CAN_MESSAGE_EMPLOYER,
    PERMISSIONS.CAN_SEE_ANALYTICS,
  ],
  [USER_ROLES.EMPLOYER]: [
    PERMISSIONS.CAN_POST_JOB,
    PERMISSIONS.CAN_EDIT_JOB,
    PERMISSIONS.CAN_DELETE_JOB,
    PERMISSIONS.CAN_VIEW_APPLICANTS,
    PERMISSIONS.CAN_UPDATE_APPLICATION_STATUS,
    PERMISSIONS.CAN_SEE_ANALYTICS,
  ],
  [USER_ROLES.ADMIN]: [
    PERMISSIONS.CAN_POST_JOB,
    PERMISSIONS.CAN_EDIT_JOB,
    PERMISSIONS.CAN_DELETE_JOB,
    PERMISSIONS.CAN_APPROVE_COMPANY,
    PERMISSIONS.CAN_MANAGE_USERS,
    PERMISSIONS.CAN_VIEW_AUDIT_LOGS,
    PERMISSIONS.CAN_BAN_USER,
    PERMISSIONS.CAN_SEE_ANALYTICS,
  ],
};

export const roleHasPermission = (role, permission) => {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
};

export const userCan = (user, permission) => {
  if (!user || !user.role) return false;
  return roleHasPermission(user.role, permission);
};
